---
  - name: checking if the folder logstash exists (meaning alreday installed)
    stat:
       path: "{{ dest_logstash_path }}"
    register: logstash_status

  #- name: push logstash tar gz
  #  become: yes
  #  copy:
  #    src: "{{ src_logstash_path }}/logstash-8.4.1-linux-x86_64.tar.gz"
  #    dest: /home/ubuntu/
  #    owner: ubuntu
  #    group: ubuntu
  #    mode: 0644
  #    force: no

  - name: creation du dossier logstash
    become: yes
    file: path={{ dest_logstash_path }} state=directory owner={{ user }}
    when: logstash_status.stat.exists == False

  - name: detar logstash tar gz dans le dossier logstash
    unarchive:
       src: /home/ubuntu/logstash-8.4.1-linux-x86_64.tar.gz
       dest: "{{ dest_logstash_path }}"
       remote_src: yes
    when: logstash_status.stat.exists == False

  #- name: push logstash config&project files
  #  become: yes
  #  copy:
  #     src: "{{ src_logstash_path }}myconf_logstash"
  #     dest: "{{ dest_logstash_path }}"
  #     owner: ubuntu
  #     group: ubuntu
  #     mode: 0755
  #     force: no ### ATTENTION ###

  - name: create env file
    template: src=templates/.env.j2 dest="{{ dest_logstash_path }}/myconf_logstash/.env"

  #- name: shell - export env var ## ne marche pas
  #  shell: "{{ dest_logstash_path }}myconf_logstash/.env"
  #- debug: msg="{{ lookup('env','$LS_SETTINGS_DIR', USR='ubuntu2') }} is an environment variable $LS_SETTINGS_DIR"

  #- name: shell - export LS_SETTINGS_DIR ## ne marche pas
  #  shell: "export LS_SETTINGS_DIR=/home/ubuntu/logstash/myconf_logstash/config"
  #  with_items: "{{ lookup('file', '{{ dest_logstash_path }}/myconf_logstash/.env').splitlines() }}"

  - name: ajout d'une ligne dans le .profile
    lineinfile:
      path: /home/{{ user }}/.profile
      line: "export {{ item }}"
    with_items: "{{ lookup('file', 'templates/.env.j2').splitlines() }}"

  - name: echo my_env_var
    shell: "echo $LS_SETTINGS_DIR"

  - name: Check env variables (print values)
    shell: "echo $LS_SETTINGS_DIR"
    register: os_info
  - debug: msg="{{os_info.stdout_lines}}"

  - name: print vault
    shell:
      cmd: "echo vault"
  - debug: msg="{{ author }}"

  - name: create logstash keystore
    shell:
      cmd: "{{ dest_logstash_path }}logstash-8.4.1/bin/logstash-keystore create --path.settings $LS_SETTINGS_DIR"
