---
- name: installation
  hosts: http1
  remote_user: ubuntu
  become: yes
  gather_facts: no
  vars:
    user: ubuntu
    domain: local.dev
    repo: git@github.com:remiliance/incident.git
    dest_logstash_path: /home/{{ user }}/logstash/
    src_logstash_path: /home/remi/Documents/ansible/ansible_incident/roles/logstash/vars/
    #repo: https://github.com/remiliance/Calculatrice.git
    registry: registry.gitlab.com/remiliance/registrydockerimage
  vars_files:
      - ./roles/logstash/vars/logstash-my-secrets.yml
  environment:
    MY_ENV_VARIABLE: whatever_value
  roles:
    - utils
    #- user
    #- nginx
    - git
    #- logstash

...
