---
- name: installation
  hosts: http1
  remote_user: ubuntu
  become: yes
  gather_facts: no
  vars:
    user: ubuntu
    domain: local.dev
    repo: git@github.com:remiliance/incident.git
    #repo: https://github.com/remiliance/Calculatrice.git
    registry: registry.gitlab.com/remiliance/registrydockerimage

  roles:
    #- utils
    #- user
    #- nginx
    - git

...
